# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a273095018feb90cf81102d89bf748b41ca418d361a30c130148695499081650ca3b4f61854a1bac36179055425785ab5321a2ac5455bcc022755e451a7f7db7

test:
  secret_key_base: 0d130abe9f718622651df25a7cd973db143af8b272ba2a3c7c00a00019aaae470b412240006f47764b6c433896915d5a1dc01b293dd2ffa9cb67e4316e69547b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
